export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const REMOVE_ACCESS_TOKEN = "REMOVE_ACCESS_TOKEN";
export const SET_CONNECTED_USER = "SET_CONNECTED_USER";
export const REMOVE_CONNECTED_USER = "REMOVE_CONNECTED_USER";
